NOTE_CONTENT_MAX_LENGTH = 20_000
NOTE_NAME_MIN_LENGTH = 1
NOTE_NAME_MAX_LENGTH = 255

NOTE_PAGE_SIZE = 10
NOTE_PAGE_LIMIT_MAX = 25

SENTENCE_TRANSFORMERS_MODEL = 'all-MiniLM-L6-v2'
SENTENCE_TRANSFORMERS_EMBEDDING_SIZE = 384
