"""Create the embedding column.

Revision ID: aee8b2a9dbc1
Revises: ec1005e02a7a
Create Date: 2025-10-24 17:41:10.471846

"""

from typing import Sequence, Union

import pgvector
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aee8b2a9dbc1'
down_revision: Union[str, Sequence[str], None] = 'ec1005e02a7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'note', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'embedding')
    # ### end Alembic commands ###
